name: fbl
description: "A new Flutter package."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ########################################## BASE ########################################
  # config文件夹
  package_info_plus: 8.1.0                      # 获取包名信息(全平台) https://pub.dev/packages/package_info_plus
  device_info_plus: 11.1.0                      # 获取设备信息(全平台) https://pub.flutter-io.cn/packages/device_info_plus
  # db文件夹
  sqflite_common_ffi: 2.3.3                     # SQLite3数据库存储(全平台) https://pub.dev/packages/sqflite_common_ffi
  shared_preferences: 2.3.2                     # 本地Key-Value文件存储(全平台) https://pub.dev/packages/shared_preferences
  # http文件夹
  dio: 5.7.0                                    # HTTP请求(dart包) https://pub.flutter-io.cn/packages/dio
  # resource文件夹
  json_annotation: 4.9.0                        # Json序列化(dart包) https://pub.dev/packages/json_annotation
  # utils文件夹
  path_provider: 2.1.5                          # 获取本地文件路径(全平台) https://pub.dev/packages/path_provider
  # widgets文件夹
  bot_toast: 4.1.3                              # Toast(flutter包) https://pub.flutter-io.cn/packages/bot_toast
  cached_network_image: 3.4.1                   # 图片多级缓存 https://pub.flutter-io.cn/packages/cached_network_image
  flutter_cache_manager: 3.4.1                  # 缓存管理工具 https://pub.flutter-io.cn/packages/flutter_cache_manager
  photo_view: 0.15.0                            # 图片预览控件(全平台) https://pub.flutter-io.cn/packages/photo_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0                          # lints检测 https://pub.flutter-io.cn/packages/flutter_lints

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
