name: dbl
description: "A new Flutter package."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ########################################## 桌面端插件 ########################################
  window_manager: 0.4.2                         # 桌面端窗口管理 https://pub.flutter-io.cn/packages/window_manager
  tray_manager: 0.2.4                           # 桌面端系统托盘 https://pub.flutter-io.cn/packages/tray_manager
  hotkey_manager: 0.2.3                         # 桌面端快捷键 https://pub.flutter-io.cn/packages/hotkey_manager
  contextual_menu: 0.1.2                        # 桌面应用创建原生上下文菜单 https://pub.flutter-io.cn/packages/contextual_menu
  desktop_multi_window: 0.2.0                   # 桌面端多窗口管理 https://pub.flutter-io.cn/packages/desktop_multi_window
  desktop_drop: 0.5.0                           # 桌面端文件拖动处理 https://pub.flutter-io.cn/packages/desktop_drop
  pasteboard: 0.3.0                             # 桌面端剪贴板 https://pub.flutter-io.cn/packages/pasteboard
  windows_single_instance: 1.0.1                # 桌面端(Windows)单实例应用 https://pub.flutter-io.cn/packages/hotkey_manager
  media_kit: 1.1.11                             # 音频全平台核心依赖 https://pub.flutter-io.cn/packages/media_kit
  media_kit_video: 1.2.5                        # 音频渲染组件 https://pub.flutter-io.cn/packages/media_kit_video
  video_player_media_kit: 1.0.5                 # 视频播放全平台核心依赖 https://pub.flutter-io.cn/packages/video_player_media_kit
  media_kit_libs_macos_video: 1.1.4             # 视频播放(macOS端) https://pub.flutter-io.cn/packages/media_kit_libs_macos_video
  media_kit_libs_windows_video: 1.0.10          # 视频播放(Windows端) https://pub.flutter-io.cn/packages/media_kit_libs_windows_video
  media_kit_libs_linux: 1.1.3                   # 视频播放(Linux端) https://pub.flutter-io.cn/packages/media_kit_libs_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
