/// Flutter icons CustomIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData heart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_big = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_big = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_big = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_big = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_dir = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_dir = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_dir = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_dir = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_hand = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_hand = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_hand = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_hand = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_cw = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccw = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData off = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_1 = IconData(0xeb9f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty = IconData(0xeba0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_1 = IconData(0xeba1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xeba2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circled = IconData(0xeba3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xeba4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_1 = IconData(0xeba5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = IconData(0xeba6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled = IconData(0xeba7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xeba8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circled = IconData(0xeba9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled2 = IconData(0xebaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled2 = IconData(0xebab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large = IconData(0xebac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th = IconData(0xebad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled = IconData(0xebae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xebaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_1 = IconData(0xebb0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 = IconData(0xebb1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xebb2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xebb3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xebb4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xebb5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xebb6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags = IconData(0xebb7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_1 = IconData(0xebb8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_1 = IconData(0xebb9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xebba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down = IconData(0xebbb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xebbc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xebbd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_1 = IconData(0xebbe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xebbf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_empty = IconData(0xebc0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xebc1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xebc2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_ext = IconData(0xf08e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_empty = IconData(0xf096, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_empty = IconData(0xf097, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_squared = IconData(0xf098, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_alt = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_cloud = IconData(0xf0ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_cloud = IconData(0xf0ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_alt = IconData(0xf0f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_squared = IconData(0xf0fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_left = IconData(0xf100, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_right = IconData(0xf101, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_up = IconData(0xf102, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_down = IconData(0xf103, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_empty = IconData(0xf10c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle = IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_1 = IconData(0xf112, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_empty = IconData(0xf11d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_all = IconData(0xf122, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_1 = IconData(0xf128, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xf130, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute = IconData(0xf131, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt = IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis_vert = IconData(0xf142, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_squared = IconData(0xf146, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_ext_alt = IconData(0xf14c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_alt = IconData(0xf164, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down_alt = IconData(0xf165, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xf175, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xf176, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xf177, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xf178, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xf1d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_empty = IconData(0xf1d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_1 = IconData(0xf1e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off = IconData(0xf1f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off_empty = IconData(0xf1f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf1f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_off = IconData(0xf204, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_on = IconData(0xf205, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus = IconData(0xf221, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars = IconData(0xf222, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_plus_o = IconData(0xf271, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_minus_o = IconData(0xf272, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_times_o = IconData(0xf273, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_check_o = IconData(0xf274, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envira = IconData(0xf299, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData font_awesome = IconData(0xf2b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
